parameters:
  artifactFeed: ''
  appName: ''

stages:
  - stage: BuildMvn
    dependsOn: [Version, ExtractVersion]
    variables:
      semver: $[stageDependencies.Version.GitVersion.outputs['gitversion.GitVersion.SemVer']]
      majorMinorPatch: $[stageDependencies.Version.GitVersion.outputs['gitversion.GitVersion.MajorMinorPatch']]
      omVersionMvn: $[stageDependencies.ExtractVersion.OpenmetadataVersion.outputs['Version.OM_VERSION_MVN']]
    jobs:
      - job: Build_and_Publish_mvn
        displayName: Build & Publish MVN
        steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
          - bash: |
              export ARTIFACT_VERSION=`echo "${OMVERSION}-dap-${MAJORMINORPATCH}"`
              echo "##vso[task.setvariable variable=artifactVersion]${ARTIFACT_VERSION}"
            displayName: Set PROD  version
            condition: eq(variables.isMain, true)
            env:
              MAJORMINORPATCH: $(majorMinorPatch)
              OMVERSION: $(omVersionMvn)
          - bash: |
              export ARTIFACT_VERSION=`echo "${OMVERSION}-dap-${SEMVER}"`
              echo "##vso[task.setvariable variable=artifactVersion]${ARTIFACT_VERSION}"
            displayName: Set DEV version
            condition: eq(variables.isMain, false)
            env:
              SEMVER: $(semver)
              OMVERSION: $(omVersionMvn)
          - script: |
              sudo apt-get install -qq -y jq
              sudo make install_antlr_cli
              mvn versions:set -DnewVersion=$(artifactVersion)
              mvn clean package -DskipTests
            displayName: GenerateOpenMetadataTarball
          - task: UniversalPackages@0
            displayName: Publish Open Metadata tarball
            inputs:
              command: publish
              publishDirectory: $(Build.SourcesDirectory)/openmetadata-dist/target/openmetadata-$(artifactVersion).tar.gz
              vstsFeedPublish: $(artifactFeed)
              vstsFeedPackagePublish: $(appName)
              versionOption: custom
              versionPublish: $(artifactVersion)
              packagePublishDescription: "Open Metadata DAP bundle"