# E2E Labels when source files are changes
e2eSettings:
  - "openmetadata-ui/**/*setting*"

e2eDataAssets:
  - "openmetadata-ui/**/*database*"
  - "openmetadata-ui/**/*table*"
  - "openmetadata-ui/**/*topic*"
  - "openmetadata-ui/**/*dashboard*"
  - "openmetadata-ui/**/*pipeline*"
  - "openmetadata-ui/**/*mlmodel*"
  - "openmetadata-ui/**/*container*"
  - "openmetadata-ui/**/*serachindex*"
  - "openmetadata-ui/**/*task*"
  - "openmetadata-ui/**/*search*"
  - "openmetadata-ui/**/*mydata*"
  - "openmetadata-ui/**/*explore*"

e2eGovernance:
  - "openmetadata-ui/**/*glossary*"
  - "openmetadata-ui/**/*tag*"
  - "openmetadata-ui/**/*domain*"

e2eObservability:
  - "openmetadata-ui/**/*alert*"
  - "openmetadata-ui/**/*incidentmanager*"
  - "openmetadata-ui/**/*metric*"
  - "openmetadata-ui/**/*dataquality*"
  - "openmetadata-ui/**/*datainsight*"
  - "openmetadata-ui/**/*observability*"

e2eIntegration:
  - "openmetadata-ui/**/*integration*"
  - "openmetadata-ui/**/*ingestion*"
  - "openmetadata-ui/**/*service*"
