# Add here any member that should belong to either a specific team,
# or that can have the tests automatically validated to run safely.

"safe to test":
  - '@ayush-shah'
  - '@OnkarVO7'
  - '@TeddyCr'
  - '@ulixius9'
  - '@pmbrull'
  - '@aniketkatkar97'
  - '@Ashish8689'
  - '@chirag-madlani'
  - '@Sachin-chaurasiya'
  - '@shahsank3t'
  - '@ShaileshParmar11'
  - '@karanh37'
  - '@harshach'
  - '@mohityadav766'
  - '@sureshms'
  - '@akash-jain-10'
  - '@tutte'
  - '@IceS2'
  - '@sushi30'
  - '@snyk-bot'
  - '@dependabot'
  - '@harshsoni2024'
  - '@SumanMaharana'
  - '@Prajwal214'

ingestion:
  - '@ayush-shah'
  - '@OnkarVO7'
  - '@TeddyCr'
  - '@ulixius9'
  - '@pmbrull'
  - '@IceS2'
  - '@sushi30'
  - '@harshsoni2024'
  - '@SumanMaharana'

UI:
  - '@aniketkatkar97'
  - '@Ashish8689'
  - '@chirag-madlani'
  - '@Sachin-chaurasiya'
  - '@shahsank3t'
  - '@ShaileshParmar11'
  - '@karanh37'

backend:
  - '@harshach'
  - '@mohityadav766'
  - '@sureshms'

devops:
  - '@akash-jain-10'
  - '@tutte'
