source:
  type: SAS
  serviceName: plover
  serviceConnection:
    config:
      type: SAS
      hostPort: https://daily.plover-m1.unx.sas.com
      username: username
      password: password
      databaseServiceName: ["plover"] # create database service and messaging service and pass `service name` here
      messagingServiceName: []
      entity_type: Table
  sourceConfig:
    config:
      type: metadata
sink:
  type: metadata-rest
  config: {}
workflowConfig:
  loggerLevel: INFO  # DEBUG, INFO, WARNING or ERROR
  openMetadataServerConfig:
    hostPort: "http://localhost:8585/api"
    authProvider: openmetadata
    securityConfig:
      jwtToken: "eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZyIsInN1YiI6ImluZ2VzdGlvbi1ib3QiLCJlbWFpbCI6ImluZ2VzdGlvbi1ib3RAb3Blbm1ldGFkYXRhLm9yZyIsImlzQm90Ijp0cnVlLCJ0b2tlblR5cGUiOiJCT1QiLCJpYXQiOjE2OTQ0NjEzNjYsImV4cCI6bnVsbH0.ANAfzVu5WecwGQ9Cm3rPyHT3JXdburLmdjxdhvM7ivJUGSV7s2-_hsFefGgHy_e20vgyP8lUo968hb-oa9E5Fzl-Rya8MBjxQ9s7Iv86vqZSkH51k8I_nP9EgddYjL00lnJguxGCvebFr1q9Ws2C0E07ltRiDkm25egsWEfiRaOoIGgy3rHP6L_H24_K7rg-nDPvoNdxjHayCmj49VrKtY3zcdCCJrWpb83qjbhsyN_liOxN6zp7qbrWxmFDv1xxGGq8KGUue6DiVS1_-YCN3-QM_1Ti4PNYsqQXzLwkyMcQl_sZzRn5VDbp8HZkRiLey-Xw1-XA3FuBtBhSIY9rTw"
    ## If SSL, fill the following
    # verifySSL: validate  # or ignore
    # sslConfig:
    #   certificatePath: /local/path/to/certificate
