name: Get Approval

on:
  pull_request:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "PRs from external contributors require an approval from the OpenMetadata team."
