name: docker-openmetadata-db docker
on:
  release:
    types: [published]

jobs:
  push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_OPENMETADATA_USERNAME }}
          password: ${{ secrets.DOCKERHUB_OPENMETADATA_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'release' }}
          # Update tags before every release
          tags: 'openmetadata/db:0.6.0,openmetadata/db:latest'
          file: ./docker/local-metadata/Dockerfile_mysql