#  Copyright 2021 Collate
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: IP Test

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:

      - name: Extract IP
        run: echo "::set-output name=runner_ip::$(curl -sS https://api.ipify.org)"
        
      - name: Display IP
        run: echo "Runner's IP address is ${{ steps.extract-ip.outputs.runner_ip }}"

      - name: Get Runner IP
        id: runner-ip
        run: echo "::set-output name=ip_address::${{ github.event.workflow_run.runner.ip_address }}"

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}