name: Validate Pydantic Models

on:
  pull_request:
    branches:
      - main
    paths:
      - 'catalog-rest-service/src/main/resources/json/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Ubuntu related dependencies
        run: |
          sudo apt-get install -y libsasl2-dev unixodbc-dev python3-venv
      - name: Install Python & dev dependencies
        run: |
          python3 -m venv env
          source env/bin/activate
          make install_dev
      - name: Generate models
        run: |
          source env/bin/activate
          make generate
