name: Schemas Script
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 12.x

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install jsonschema2md
        run: sudo npm install -g @adobe/jsonschema2md

      - name: Changing $ref
        run: sed -i '71s+"#/definitions/tag"+"#"+' catalog-rest-service/src/main/resources/json/schema/entity/tags/tagCategory.json

      - name: Json schema to markdown
        run: jsonschema2md -d catalog-rest-service/src/main/resources/json/schema -o docs/openmetadata-apis/schemas/SchemaMarkdown -e json

      - name: Changing $ref
        run: sed -i '71s+"#"+"#/definitions/tag"+' catalog-rest-service/src/main/resources/json/schema/entity/tags/tagCategory.json

      - name: Running header script
        run: sh ./scripts/header.sh

      - name: Generating directories
        run: sh ./scripts/generateDirectories.sh

      - name: Configuring paths
        run: sh ./scripts/editContent.sh

      - name: Deploy 🚀
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: ./
          branch: main
