name: Trivy Security Scan for Docker Images

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  trivy-scan:
    name: Build & Scan Docker Images with Trivy
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Build & Push Docker Images (fetch from prepare-for-docker-build-and-push)
      - name: Build & Push Docker Images
        id: docker_build
        uses: ./.github/actions/prepare-for-docker-build-and-push
        with:
          image: openmetadata/server
          tag: ${{ inputs.docker_release_tag }}
          push_latest: false
          is_ingestion: false
          release_version: latest
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Run Trivy Scan on the Built Image
      - name: Run Trivy Scan on the Image
        run: |
          trivy image --ignore-unfixed --severity HIGH,CRITICAL openmetadata/server:${{ inputs.docker_release_tag }} > trivy-results.txt

      # Step 4: Format Trivy Output for PR Comment
      - name: Format Trivy Output
        run: |
          echo "## 🚨 Trivy Security Scan Results 🚨" > trivy-results.md
          echo "" >> trivy-results.md

          if [[ -s trivy-results.txt ]]; then
            echo "### 🔴 Vulnerabilities Found:" >> trivy-results.md
            echo '\`\`\`' >> trivy-results.md
            cat trivy-results.txt >> trivy-results.md
            echo '\`\`\`' >> trivy-results.md
          else
            echo "✅ No HIGH or CRITICAL vulnerabilities found." >> trivy-results.md
          fi

      # Step 5: Post Results as PR Comment
      - name: Comment Trivy Scan Results on PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: trivy-results.md
