name: TypeScript Type Generation

on:
  pull_request:
    paths:
      - 'openmetadata-spec/src/main/resources/json/schema/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
        type: string

jobs:
  generate-types:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Workflow triggered successfully on branch ${{ github.event.inputs.branch || github.ref_name }}"